version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dotnetapitest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-v6te8y6qc0x1"
s3_prefix = "dotnetapitest"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
